//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinDE.rc
//
#define IDR_MANIFEST                    1
#define IDC_MOB_COUNT                   101
#define IDD_WINDE_DIALOG                102
#define IDC_ROOM_COUNT                  102
#define IDC_OBJ_COUNT                   103
#define IDC_QUEST_COUNT                 104
#define IDC_SHOP_COUNT                  105
#define IDC_SAVE_FORMAT                 106
#define IDC_SPLIT                       107
#define IDC_SPLITTER1                   108
#define IDT_AUTO_SAVE                   109
#define ID_HISTORY_0                    110
#define ID_TREE_EDIT_FRIENDS            112
#define ID_TREE_FRIENDS                 112
#define IDD_CANNON_TAB                  113
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDR_EDIT_ACCELS                 129
#define IDD_EDIT_ROOM                   130
#define IDR_COLOREDITCTX                130
#define IDD_EDIT_EXITS                  132
#define IDI_DOOR                        133
#define ID_HISTORY_24                   135
#define IDD_ENTER_VNUM                  137
#define IDD_EXTRA_DESC                  138
#define IDD_ROOM_FLAGS                  140
#define IDD_VNUM_LIST                   141
#define IDD_EDIT_AREA                   142
#define IDD_EDIT_MOB                    145
#define IDD_EDIT_SHOP                   147
#define IDD_ACT_FLAGS                   148
#define IDD_EDIT_MOB_AFFECTS            149
#define IDD_SPEECH_QUEST                153
#define IDD_ITEM_QUEST                  154
#define IDD_SELECT_QUEST                156
#define IDD_EDIT_OBJECT                 157
#define IDD_OBJ_EXTRA_FLAGS             158
#define IDD_EDIT_CONTENTS               159
#define IDD_EDIT_ANTI_FLAGS             160
#define IDD_EQUIP_MOB                   161
#define IDD_ADD_EQ_ITEM                 162
#define IDR_TOOLBAR1                    168
#define IDR_MENU2                       183
#define IDD_CREATE_GRID                 187
#define IDB_TREE_MOB                    188
#define IDB_TREE_OBJ                    189
#define IDB_TREE_ROOM                   190
#define IDB_TREE_AREA                   191
#define IDB_TREE_OBJ_INDEX              192
#define IDB_TREE_MOB_INDEX              193
#define IDB_TREE_CONTENTS               194
#define IDB_TREE_PEOPLE                 195
#define IDB_TREE_ROOMS                  196
#define IDB_TREE_MOBS                   197
#define IDB_TREE_OBJS                   198
#define IDD_DIRECTIONS                  202
#define IDD_SETTINGS                    203
#define IDD_COLORS                      234
#define IDB_BLACK                       254
#define IDB_YELLOW                      255
#define IDB_GREEN                       256
#define IDB_CYAN                        257
#define IDB_BLUE                        258
#define IDB_MAGENTA                     259
#define IDB_RED                         260
#define IDB_WHITE                       261
#define IDD_SAVE                        262
#define IDR_TRAY_MENU                   263
#define IDD_GUARD_FLAGS                 264
#define IDD_EDIT_OBJ                    266
#define IDD_MAP                         267
#define IDR_MAP_TOOLS                   268
#define IDI_ROOM_BASE                   272
#define IDI_FIRE_PLANE                  279
#define IDI_FOREST                      280
#define IDI_WATER                       281
#define IDI_WATER_NOSWIM                282
#define IDI_SWAMP                       283
#define IDI_OCEAN                       284
#define IDI_AIR                         285
#define IDI_ROAD                        286
#define IDI_INSIDE                      287
#define IDI_WATER_PLANE                 288
#define IDI_ARTIC                       289
#define IDI_FIELD                       290
#define IDI_HILLS                       291
#define IDI_DESERT                      292
#define IDI_CITY                        293
#define IDI_MOUNTAIN                    294
#define IDI_ASTRAL_PLANE                295
#define IDI_PLANE_AIR                   296
#define IDI_PLANE_ETHEREAL              297
#define IDI_NOGROUND                    298
#define IDI_U_INSIDE                    299
#define IDI_U_WATER                     300
#define IDI_U_WATER_NOSWIM              301
#define IDI_U_OCEAN                     302
#define IDI_U_NOPASS                    303
#define IDI_PLANE_EARTH                 304
#define IDI_U_CITY                      305
#define IDI_U_WILD                      306
#define IDI_UNDERWATER                  307
#define IDI_UNDERWATER_GROUND           308
#define IDR_MAP_MENU                    309
#define IDD_QUEST_EDIT                  310
#define IDD_ADD_QUEST_ITEM              312
#define IDD_QUEST_CLUE                  313
#define IDD_EDIT_QUEST                  314
#define IDD_COINS                       316
#define IDD_SPELLS                      317
#define IDD_EDIT_FRIENDS                318
#define IDD_EDIT_TRAP                   321
#define IDD_SHIPBUILDER                 325
#define IDD_AMMO_TAB                    327
#define IDD_CREW_TAB                    328
#define IDD_CANNON_BUILDER              329
#define IDD_AMMO_BUILDER                330
#define IDD_CREW_BUILDER                331
#define IDD_AGGRO_STATS                 333
#define IDD_STATISTICS                  335
#define IDD_MOB_VIEW                    336
#define IDD_CLASS_STATS                 337
#define IDD_RACE_STATS                  339
#define IDD_ROOM_VIEW                   341
#define IDD_OBJ_VIEW                    346
#define IDD_TYPE_VIEW                   347
#define IDD_MAT_VIEW                    349
#define IDD_CRAFT_VIEW                  351
#define IDD_EXTENDED_STATS              353
#define IDI_ICON1                       355
#define IDD_STAT_VIEW                   356
#define IDD_PROG_EDIT                   358
#define IDD_SELECT_AFF                  360
#define IDD_ABOUT                       361
#define IDD_CUSTOM_FILE                 362
#define IDD_BVCALCUTATOR_DIALOG         363
#define IDD_EDIT_AFF_BITS               364
#define IDC_TEXT                        1000
#define IDC_ZONETREE                    1001
#define IDC_COMMAND                     1002
#define IDC_ENTER                       1003
#define IDC_BV00                        1003
#define IDC_WALKCREATE                  1004
#define IDC_CONVERT                     1004
#define IDC_NORTHWEST                   1005
#define IDC_CLEAR                       1005
#define IDC_NORTH                       1006
#define IDC_NORTHEAST                   1007
#define IDC_WEST                        1008
#define IDC_EAST                        1009
#define IDC_SOUTHWEST                   1010
#define IDC_LOOK                        1011
#define IDC_SOUTH                       1012
#define IDC_SOUTHEAST                   1013
#define IDC_EDITROOM                    1014
#define IDC_NEWMOB                      1015
#define IDC_EDITOBJECT                  1016
#define IDC_SAVE                        1017
#define IDC_NEWROOM                     1018
#define IDC_EDITMOB                     1019
#define IDC_NEWOBJECT                   1020
#define IDC_SETTINGS                    1021
#define IDC_DISPLAY                     1022
#define IDC_EDIT_ROOM_VNUM              1024
#define IDC_EDIT_ROOM_NAME              1025
#define IDC_EDIT_ROOM_DESC              1026
#define IDC_SECTOR                      1027
#define IDC_EXTRA_DESCS                 1028
#define IDC_EDIT_EXITS                  1029
#define IDC_CURRENT_STRENGTH            1030
#define IDC_CURRENT_DIR                 1032
#define IDC_FALL_CHANCE                 1033
#define IDC_LIGHTING                    1034
#define IDC_ROOM_FLAGS                  1035
#define IDC_AREA_EDIT                   1039
#define IDC_BV08                        1044
#define IDC_BV10                        1045
#define IDC_BV09                        1046
#define IDC_BV01                        1047
#define IDC_BV02                        1048
#define IDC_BV03                        1049
#define IDC_BV16                        1050
#define IDC_EXIT_KEYWORD                1051
#define IDC_BV11                        1051
#define IDC_STATIC_DIR                  1052
#define IDC_BV17                        1052
#define IDC_TO_ROOM                     1053
#define IDC_BV18                        1053
#define IDC_EXIT_DESC                   1054
#define IDC_BV19                        1054
#define IDC_ROOM_LIST                   1055
#define IDC_BV24                        1056
#define IDC_EXIT_NW                     1057
#define IDC_BV25                        1057
#define IDC_EXIT_NORTH                  1058
#define IDC_BV26                        1058
#define IDC_EXIT_NE                     1059
#define IDC_BV27                        1059
#define IDC_EXIT_WEST                   1060
#define IDC_BV29                        1060
#define IDC_BV31                        1061
#define IDC_EXIT_EAST                   1062
#define IDC_BV21                        1062
#define IDC_EXIT_SW                     1063
#define IDC_BV05                        1063
#define IDC_EXIT_SOUTH                  1064
#define IDC_BV12                        1064
#define IDC_EXIT_SE                     1065
#define IDC_BV04                        1065
#define IDC_EXIT_UP                     1066
#define IDC_BV07                        1066
#define IDC_EXIT_DOWN                   1067
#define IDC_BV06                        1067
#define IDC_BV23                        1068
#define IDC_KEY_VNUM                    1069
#define IDC_BV30                        1069
#define IDC_KEY_LIST                    1070
#define IDC_BV13                        1070
#define IDC_HAS_DOOR                    1071
#define IDC_BV14                        1071
#define IDC_SECRET                      1072
#define IDC_BV15                        1072
#define IDC_LOCKED                      1073
#define IDC_BV22                        1073
#define IDC_PICK_PROOF                  1074
#define IDC_BV28                        1074
#define IDC_PASS_PROOF                  1075
#define IDC_BV20                        1075
#define IDC_BASH_PROOF                  1076
#define IDC_CLOSED                      1077
#define IDC_EAT_KEY                     1078
#define IDC_BLOCKED                     1079
#define IDC_TRAPPED                     1080
#define IDC_BASHED                      1081
#define IDC_SPIKED                      1082
#define IDC_EXIT_TRAP_LEVEL             1083
#define IDC_EXIT_TRAP_TYPE              1084
#define IDC_EXIT_TRAP_CHARGES           1085
#define IDC_ENTER_VNUM                  1088
#define IDC_EXTRA_DESC                  1089
#define IDC_ADD_DESC                    1090
#define IDC_PREV_DESC                   1091
#define IDC_DESC_NEXT                   1092
#define IDC_DELETE_DESC                 1093
#define IDC_EXTRA_KEYS                  1094
#define IDC_DARK                        1097
#define IDC_LIMITSCAN                   1098
#define IDC_SAFE                        1099
#define IDC_NO_MOB                      1100
#define IDC_INDOORS                     1101
#define IDC_SILENT                      1102
#define IDC_UNDERWATER                  1103
#define IDC_NO_RECALL                   1104
#define IDC_NO_MAGIC                    1105
#define IDC_TUNNEL                      1106
#define IDC_PRIVATE                     1107
#define IDC_NOCAMP                      1108
#define IDC_NO_PRECIP                   1109
#define IDC_JAIL                        1110
#define IDC_NO_TELEPORT                 1111
#define IDC_SOLITARY                    1112
#define IDC_HEAL                        1113
#define IDC_NO_GATE                     1114
#define IDC_NO_HEAL                     1115
#define IDC_INN                         1116
#define IDC_DOCKABLE                    1117
#define IDC_MAGICDARK                   1118
#define IDC_MAGICLIGHT                  1119
#define IDC_NOSUMMON                    1120
#define IDC_GUILDROOM                   1121
#define IDC_TWILIGHT                    1122
#define IDC_NO_PSIONICS                 1123
#define IDC_BANK                        1124
#define IDC_PET_SHOP                    1125
#define IDC_NO_SCAN                     1126
#define IDC_ARENA                       1127
#define IDC_TREASUREROOM                1128
#define IDC_DELETE_ROOM                 1129
#define IDC_SELETECT_FROM_LIST          1130
#define IDC_VNUM_LIST                   1132
#define IDC_NEW_AREA                    1133
#define IDC_OPEN                        1138
#define IDC_EXIT                        1139
#define IDC_STARTING_VNUM               1140
#define IDC_AREA_NAME                   1141
#define IDC_SAVE_AS                     1142
#define IDC_JUSTICE                     1143
#define IDC_DEFENDER_VNUM               1144
#define IDC_DEFENDER_LIST               1145
#define IDC_BARRACKS_VNUM               1146
#define IDC_AUTHOR                      1147
#define IDC_LOW_LEVEL                   1148
#define IDC_HIGH_LEVEL                  1149
#define IDC_BARRACKS_LIST               1150
#define IDC_JAIL_VNUM                   1151
#define IDC_JAIL_LIST                   1152
#define IDC_SQUADS                      1153
#define IDC_JUDGE_VNUM                  1154
#define IDC_JUDGE_LIST                  1155
#define IDC_RESET_MODE                  1156
#define IDC_LOW_RESET                   1157
#define IDC_HIGH_RESET                  1158
#define IDC_RESET_MESSAGE               1159
#define IDC_AREA_SILENT                 1160
#define IDC_AREA_SAFE                   1161
#define IDC_AREA_HOMETOWN               1162
#define IDC_AREA_NO_TELEPORT            1163
#define IDC_MOB_VNUM                    1168
#define IDC_MOB_SHORT                   1170
#define IDC_MOB_LONG                    1171
#define IDC_MOB_KEYWORDS                1172
#define IDC_MOB_DESC                    1173
#define IDC_MOB_RACE                    1174
#define IDC_MOB_CLASS                   1175
#define IDC_MOB_SEX                     1176
#define IDC_MOB_SIZE                    1177
#define IDC_MOB_LEVEL                   1178
#define IDC_MOB_POSITION                1179
#define IDC_MOB_ALIGN                   1180
#define IDC_MOB_AFFECTS                 1181
#define IDC_MOB_SHOP                    1185
#define IDC_SPEECH_QUEST                1186
#define IDC_QUESTS                      1186
#define IDC_ITEM_QUEST                  1187
#define IDC_MOB_ACT                     1189
#define IDC_DELETE                      1190
#define IDC_DELETE_SHOP                 1191
#define IDC_TYPE_LIST                   1193
#define IDC_SALE_ITEMS                  1194
#define IDC_ADD_ITEM                    1195
#define IDC_SELL_PROFIT                 1196
#define IDC_BUY_PROFIT                  1197
#define IDC_OPENS                       1198
#define IDC_CLOSES                      1199
#define IDC_SIZEMINUS                   1200
#define IDC_REMOVE_ITEM                 1200
#define IDC_SENTINAL                    1201
#define IDC_SCAVENGER                   1202
#define IDC_GUARDIAN                    1204
#define IDC_AGGRESSIVE                  1205
#define IDC_STAY_AREA                   1206
#define IDC_WIMPY                       1207
#define IDC_AGGROEVIL                   1208
#define IDC_AGGROGOOD                   1209
#define IDC_AGGRONEUT                   1210
#define IDC_MEMORY                      1211
#define IDC_NOPARA                      1212
#define IDC_NOBASH                      1214
#define IDC_TEACHER                     1215
#define IDC_WITNESS                     1216
#define IDC_CANFLY                      1217
#define IDC_CANSWIM                     1218
#define IDC_CANT_TK                     1219
#define IDC_PET                         1221
#define IDC_NOEXP                       1222
#define IDC_SIZEPLUS                    1223
#define IDC_NOCHARM                     1225
#define IDC_PROTECTOR                   1226
#define IDC_MOUNT                       1227
#define IDC_AGGROEVILRACE               1228
#define IDC_DISMOUNT                    1228
#define IDC_AGGROGOODRACE               1229
#define IDC_HUNTER                      1230
#define IDC_AFF_LIST1                   1231
#define IDC_AFF_LIST2                   1232
#define IDC_QUEST_KEYWORDS              1235
#define IDC_QUEST_RESPONSE              1236
#define IDC_ADD_SPEECH_QUEST            1239
#define IDC_REMOVE_SPEECH_QUEST         1240
#define IDC_QUEST_ITEM_LIST             1241
#define IDC_QUEST_REWARD_LIST           1242
#define IDC_BUTTON5                     1243
#define IDC_ADD_ITEM_QUEST              1243
#define IDC_DELETE_QUEST                1243
#define IDC_BUTTON6                     1244
#define IDC_REMOVE_ITEM_QUEST           1244
#define IDC_ADD_QUEST_ITEM              1245
#define IDC_REMOVE_QUEST_ITEM           1246
#define IDC_ADD_QUEST_REWARD            1247
#define IDC_REMOVE_QUEST_REWARD         1248
#define IDC_COMPLETE_MESSAGE            1249
#define IDC_DISSAPEAR_MESSAGE           1250
#define IDC_EDIT_SPEECH_QUEST           1251
#define IDC_EDIT_ITEM_QUEST             1251
#define IDC_QUEST_LIST                  1252
#define IDC_OBJ_VNUM                    1253
#define IDC_OBJ_SHORT                   1254
#define IDC_OBJ_LONG                    1255
#define IDC_OBJ_CRAFTSMANSHIP           1258
#define IDC_OBJ_WEAR_LOCS               1259
#define IDC_OBJ_MATERIAL                1260
#define IDC_OBJ_TYPE                    1261
#define IDC_VALUE1                      1262
#define IDC_VALUE2                      1263
#define IDC_VALUE3                      1264
#define IDC_VALUE4                      1265
#define IDC_VALUE5                      1266
#define IDC_VALUE6                      1267
#define IDC_VALUE7                      1268
#define IDC_OBJ_SIZE                    1269
#define IDC_OBJ_CONDITION               1270
#define IDC_OBJ_WEIGHT                  1271
#define IDC_OBJ_VOLUME                  1272
#define IDC_BUTTON1                     1273
#define IDC_EQUIP                       1273
#define IDC_ADD_INV_ITEM                1273
#define IDC_UP                          1273
#define IDC_SEL_COLOR                   1273
#define IDC_GUARD_FLAGS                 1273
#define IDC_GET_VNUM                    1273
#define IDC_CALCULATE                   1273
#define IDC_HISTORY                     1273
#define IDC_ADD_FOLLOWER                1273
#define IDC_TRAP                        1273
#define IDC_OBJ_LIST                    1273
#define IDC_EDIT_BITS                   1273
#define IDC_BITCALC                     1273
#define IDC_EXTRA_FLAGS                 1274
#define IDC_DOWN                        1274
#define IDC_ADD_REWARDS                 1274
#define IDC_REMOVE_FOLLOWER             1274
#define IDC_BITCALC2                    1274
#define IDC_OBJ_EXTRA_DESC              1275
#define IDC_BITCALC3                    1275
#define IDC_OBJ_AFF                     1276
#define IDC_BITCALC4                    1276
#define IDC_EDIT_CONTENTS               1277
#define IDC_BITCALC5                    1277
#define IDC_OBJ_LOAD                    1278
#define IDC_BITCALC6                    1278
#define IDC_ANTI_FLAGS                  1279
#define IDC_OBJ_KEYWORDS                1280
#define IDC_VALUE8                      1281
#define IDC_STATIC_VALUE1               1282
#define IDC_STATIC_VALUE2               1283
#define IDC_STATIC_VALUE3               1284
#define IDC_STATIC_VALUE4               1285
#define IDC_STATIC_VALUE5               1286
#define IDC_STATIC_VALUE6               1287
#define IDC_STATIC_VALUE7               1288
#define IDC_STATIC_VALUE8               1289
#define IDC_CONTENTS                    1291
#define IDC_OBJECT_LIST                 1292
#define IDC_REMOVE_OBJ                  1294
#define IDC_ADD_OBJ                     1295
#define IDC_VALUE1_LIST                 1296
#define IDC_VALUE2_LIST                 1297
#define IDC_VALUE3_LIST                 1298
#define IDC_VALUE4_LIST                 1299
#define IDC_VALUE5_LIST                 1300
#define IDC_VALUE6_LIST                 1301
#define IDC_VALUE7_LIST                 1302
#define IDC_VALUE8_LIST                 1303
#define IDC_REV_NORTH                   1306
#define IDC_REV_NE                      1307
#define IDC_REV_SOUTH                   1308
#define IDC_REV_NW                      1309
#define IDC_REV_EAST                    1310
#define IDC_REV_SE                      1311
#define IDC_REV_WEST                    1312
#define IDC_REV_SW                      1313
#define IDC_REV_UP                      1314
#define IDC_RADIO14                     1315
#define IDC_REVERSE_EXIT                1316
#define IDC_EQUIP_LIST                  1332
#define IDC_ADD_EQUIP_ITEM              1333
#define IDC_REMOVE_EQUIP_ITEM           1334
#define IDC_INV_LIST                    1335
#define IDC_REMOVE_INV_ITEM             1336
#define IDC_COMBO1                      1337
#define IDC_EQUIP_LOC                   1337
#define IDC_APPLY1_LIST                 1337
#define IDC_QUEST_TYPE                  1337
#define IDC_PROG_TYPE                   1337
#define IDC_LIST1                       1338
#define IDC_EQ_LIST                     1338
#define IDC_APPLY2_LIST                 1338
#define IDC_SPELLS                      1338
#define IDC_FUNCTIONS                   1338
#define IDC_REWARD_LIST                 1339
#define IDC_COMMANDS                    1339
#define IDC_VARS                        1341
#define IDC_EDIT_FRAME                  1342
#define IDC_TEMPLATE                    1342
#define IDC_ZONETREE_FRAME              1343
#define IDC_GRID_HEIGHT                 1345
#define IDC_GRID_WIDTH                  1346
#define IDC_GRID_DEPTH                  1347
#define IDC_OPEN_FORMAT                 1347
#define IDC_AUTO_SAVE                   1348
#define IDC_TIMER                       1349
#define IDC_WALK_CREATE                 1350
#define IDC_SPLITTER                    1351
#define IDC_LINE                        1352
#define IDC_DEF_DIM                     1353
#define IDC_ECHO_DIM                    1354
#define IDC_ECHO                        1358
#define IDC_DEF_COLOR                   1362
#define IDC_ECHO_COLOR                  1363
#define IDC_SAVING_PROGRESS             1363
#define IDC_SAVING                      1364
#define IDC_APPLY1_VAL                  1366
#define IDC_APPLY2_VAL                  1367
#define IDC_EDIT_REWARDS                1374
#define IDC_EDIT_WANTS                  1375
#define IDC_NEW_CLUE                    1376
#define IDC_DELETE_CLUE                 1377
#define IDC_EDIT_CLUE                   1378
#define IDC_QUEST_VALUE                 1380
#define IDC_MESSAGE                     1381
#define IDC_DISSAPEAR                   1381
#define IDC_NEW_QUEST                   1383
#define IDC_EDIT_QUEST                  1384
#define IDC_CLUE_LIST                   1385
#define IDC_KEYWORDS                    1386
#define IDC_DELETE_WANTS                1387
#define IDC_DELETE_REWARDS              1388
#define IDC_ADD_WANT                    1389
#define IDC_WANT_LIST                   1390
#define IDC_COMPLETE                    1391
#define IDC_PLATINUM                    1392
#define IDC_SILVER                      1393
#define IDC_GOLD                        1394
#define IDC_COPPER                      1395
#define IDC_TOTAL                       1396
#define IDC_TYPE                        1398
#define IDC_RIDERTXT                    1405
#define IDC_VALUE_FLAGS0                1408
#define IDC_VALUE_FLAGS1                1409
#define IDC_VALUE_FLAGS5                1410
#define IDC_LIST2                       1414
#define IDC_LIST3                       1415
#define IDC_SAVE_ON_EXIT                1416
#define IDC_DISP_LINE_LENGTH            1417
#define IDC_TRAP_LEVEL                  1417
#define IDC_TRAP_CHARGES                1418
#define IDC_TRAP_PERCENT                1419
#define IDC_LIST4                       1420
#define IDC_TRAP_DAMAGE                 1421
#define IDC_SHIPBUILDER                 1429
#define IDC_EDIT                        1430
#define IDC_CREATE                      1431
#define IDC_CREW_LIST                   1432
#define IDC_NAME                        1433
#define IDC_ACCURACY                    1434
#define IDC_RANGE                       1435
#define IDC_POWER                       1436
#define IDC_PRICE                       1437
#define IDC_OBJECT                      1438
#define IDC_SHIPWRIGHTS                 1439
#define IDC_ADD                         1440
#define IDC_REMOVE                      1441
#define IDC_CALC                        1442
#define IDC_HULL                        1445
#define IDC_SAIL                        1446
#define IDC_CREW                        1447
#define IDC_QUANTITY                    1449
#define IDC_MEMBERS                     1452
#define IDC_SPEED                       1453
#define IDC_FORTITUDE                   1454
#define IDC_STRENGTH                    1455
#define IDC_MAX_SAIL                    1458
#define IDC_ATK                         1459
#define IDC_MAX_ATK                     1460
#define IDC_GUN                         1461
#define IDC_MAX_GUN                     1462
#define IDC_DEF                         1463
#define IDC_MAX_DEF                     1464
#define IDC_MEMBER                      1466
#define IDC_MEMBER_LIST                 1467
#define IDC_LEADER                      1468
#define IDC_CANNON_LIST                 1468
#define IDC_LEADER_LIST                 1469
#define IDC_AMMO_LIST                   1469
#define IDC_FILENAME                    1470
#define IDC_MSCHART1                    1475
#define IDC_TAB1                        1476
#define IDC_SLIDER1                     1478
#define IDC_AVG_ALIGN                   1479
#define IDC_AVG_LEVEL                   1480
#define IDC_MOBS_LOADED                 1482
#define IDC_AVG_SIZE                    1483
#define IDC_SHOWLEGEND                  1484
#define IDC_BAR                         1485
#define IDC_PIE                         1486
#define IDC_3D                          1487
#define IDC_LEGEND                      1494
#define IDC_OBJS_LOADED                 1504
#define IDC_TOT_AC                      1505
#define IDC_AVG_AC                      1506
#define IDC_TOT_STR                     1507
#define IDC_TOT_RACSTR                  1508
#define IDC_AVG_MAXSTR                  1509
#define IDC_AVG_RACSTR                  1510
#define IDC_TOT_DAM                     1511
#define IDC_TOT_MAXSTR                  1511
#define IDC_AVG_DAM                     1512
#define IDC_TOT_HP                      1512
#define IDC_AVG_STR                     1513
#define IDC_AVG_HP                      1513
#define IDC_TOT_CON                     1514
#define IDC_TOT_MP                      1514
#define IDC_AVG_CON                     1515
#define IDC_AVG_MP                      1515
#define IDC_TOT_DEX                     1516
#define IDC_TOT_MV                      1516
#define IDC_AVG_DEX                     1517
#define IDC_AVG_MV                      1517
#define IDC_TOT_AGI                     1518
#define IDC_TOT_PARA                    1518
#define IDC_AVG_AGI                     1519
#define IDC_AVG_PARA                    1519
#define IDC_TOT_INT                     1520
#define IDC_TOT_ROD                     1520
#define IDC_FRAME_RECT                  1520
#define IDC_AVG_INT                     1521
#define IDC_AVG_ROD                     1521
#define IDC_EDIT_PROGS                  1521
#define IDC_TOT_WIS                     1522
#define IDC_TOT_PETRI                   1522
#define IDC_FNAME                       1522
#define IDC_AVG_WIS                     1523
#define IDC_AVG_PETRI                   1523
#define IDC_AFF_LIST                    1523
#define IDC_TOT_HIT                     1524
#define IDC_TOT_BREATH                  1524
#define IDC_AVG_HIT                     1525
#define IDC_AVG_BREATH                  1525
#define IDC_COMPANY                     1525
#define IDC_TOT_SPELL                   1526
#define IDC_VERSION                     1526
#define IDC_AVG_SPELL                   1527
#define IDC_ABOUT                       1527
#define IDC_VDATE                       1528
#define IDC_DATE                        1530
#define IDC_MAIL                        1532
#define IDC_LINK                        1533
#define IDC_ROOM_TREE                   1533
#define IDC_BIT1                        1534
#define IDC_BIT2                        1535
#define IDC_BIT3                        1536
#define IDC_BIT4                        1537
#define IDC_BIT5                        1538
#define IDC_BIT6                        1539
#define IDC_TOT_MAXCON                  1543
#define IDC_TOT_RACCON                  1544
#define IDC_AVG_MAXCON                  1545
#define IDC_AVG_RACCON                  1546
#define IDC_TOT_MAXDEX                  1547
#define IDC_TOT_RACDEX                  1548
#define IDC_AVG_MAXDEX                  1549
#define IDC_AVG_RACDEX                  1550
#define IDC_TOT_MAXAGI                  1551
#define IDC_TOT_RACAGI                  1552
#define IDC_AVG_MAXAGI                  1553
#define IDC_AVG_RACAGI                  1554
#define IDC_TOT_MAXINT                  1555
#define IDC_TOT_RACINT                  1556
#define IDC_AVG_MAXINT                  1557
#define IDC_AVG_RACINT                  1558
#define IDC_TOT_MAXWIS                  1559
#define IDC_TOT_RACWIS                  1560
#define IDC_AVG_MAXWIS                  1561
#define IDC_AVG_RACWIS                  1562
#define IDC_TOT_MAXPOW                  1563
#define IDC_TOT_RACPOW                  1564
#define IDC_AVG_MAXPOW                  1565
#define IDC_AVG_RACPOW                  1566
#define IDC_TOT_MAXLUK                  1567
#define IDC_TOT_RACLUK                  1568
#define IDC_AVG_MAXLUK                  1569
#define IDC_AVG_RACLUK                  1570
#define ID_FILE_EXIT                    32774
#define ID_AREA_PROPERTIES              32775
#define ID_ROOMS_NEWROOM                32776
#define ID_ROOMS_EDITROOM               32777
#define ID_ROOMS_DELETEROOM             32778
#define ID_MOBILES_NEWMOB               32779
#define ID_MOBILES_EDITMOB              32780
#define ID_MOBILES_DELETEMOB            32781
#define ID_OBJECTS_NEWOBJECT            32782
#define ID_OBJECTS_EDITOBJECT           32783
#define ID_OBJECTS_DELETEOBJECT         32784
#define ID_EDITOR_SETTINGS              32785
#define ID_EDITOR_HELP                  32786
#define ID_AREA_ROOMS_CREATEGRID        32788
#define ID_TOOL_NEW_ROOM                32797
#define ID_EDIT_AREA                    32798
#define ID_OPEN_AREA                    32799
#define ID_BUTTON32800                  32800
#define ID_TOOL_EDIT_ROOM               32802
#define ID_DELETE_ROOM                  32803
#define ID_TOOL_CREATE_MOB              32804
#define ID_TOOL_EDIT_MOB                32805
#define ID_TOOL_DELETE_MOB              32806
#define ID_CREATE_OBJ                   32807
#define ID_TOOL_EDIT_OBJ                32808
#define ID_DELETE_OBJECT                32809
#define ID_TOOL_NEW_AREA                32810
#define ID_SAVE_AREA                    32811
#define ID_SETTINGS                     32812
#define ID_TOOL_CREATE_GRID             32816
#define ID_TOOL_DELETE_ROOM             32817
#define ID_TOOL_DELETE_OBJ              32818
#define ID_TOOL_CREATE_OBJ              32819
#define ID_TOOL_SETTING                 32824
#define ID_TREE_EDIT_ROOM               32825
#define ID_TREE_DELETE_ROOM             32826
#define ID_TREE_CONTENTS                32827
#define ID_TREE_NEW_AREA                32828
#define ID_TREE_SAVE_AREA               32829
#define ID_TREE_OPEN_AREA               32830
#define ID_TOOL_COMPAS                  32831
#define ID_TREE_EDIT_AREA               32832
#define ID_TREE_EDIT_MOB                32833
#define ID_TREE_DELETE_MOB              32834
#define ID_TREE_EDIT_MINDEX             32835
#define ID_TREE_DELETE_MINDEX           32836
#define ID_TREE_EDIT_OINDEX             32837
#define ID_TREE_DELETE_OINDEX           32838
#define ID_TREE_EDIT_OBJ                32839
#define ID_TREE_DELETE_OBJ              32840
#define ID_TREE_CONTENTS_ROOM           32841
#define ID_TREE_NEW_ROOM                32842
#define ID_TREE_NEW_MOB                 32843
#define ID_TREE_NEW_OBJ                 32844
#define ID_TREE_ROOM_GRID               32845
#define ID_TREE_DELETE_ROOMS            32846
#define ID_TREE_DELETE_MOBS             32847
#define ID_TREE_DELETE_OBJS             32848
#define ID_TREE_REMOVE_PEOPLE           32849
#define ID_TREE_REMOVE_CONTENTS         32850
#define ID_TREE_EDIT_EQUIP              32851
#define ID_TRAYMENU_SAVE                32852
#define ID_TRAYMENU_MINIMIZE            32853
#define ID_TRAYMENU_MAXIMIZE            32854
#define ID_TRAYMENU_EXIT                32855
#define ID_TRAYMENU_CLOSE               32856
#define ID_LEVEL_UP                     32857
#define ID_LEVEL_DOWN                   32858
#define ID_CENTER                       32859
#define ID_MAPMENU_NEWROOM              32862
#define ID_MAPMENU_EDITROOM             32863
#define ID_MAPMENU_DELETEROOM           32864
#define ID_MAP                          32865
#define ID_TREE_GOTO                    32867
#define ID_TREE_EDIT_CONTENTS           32868
#define ID_TOOL_CREATE_ROOM             32870
#define ID_TOOL_SAVE_AREA               32872
#define ID_CANNON_BUILDER               32874
#define ID_AMMO_BUILDER                 32876
#define ID_BUTTON32877                  32877
#define ID_STATISTICS                   32878
#define ID_VNUM                         32879
#define ID_MAPMENU_TERRAIN_INSIDE       32889
#define ID_MAPMENU_TERRAIN_CITY         32890
#define ID_MAPMENU_TERRAIN_FIELD        32891
#define ID_MAPMENU_TERRAIN_FOREST       32892
#define ID_MAPMENU_TERRAIN_HILLS        32893
#define ID_MAPMENU_TERRAIN_MOUNTAIN     32894
#define ID_MAPMENU_TERRAIN_WATERSWIM    32895
#define ID_MAPMENU_TERRAIN_WATERNOSWIM  32896
#define ID_MAPMENU_TERRAIN_AIR          32897
#define ID_MAPMENU_TERRAIN_UNDERWATER   32898
#define ID_MAPMENU_TERRAIN_UNDERWATERGROUND 32899
#define ID_MAPMENU_TERRAIN_OCEAN        32900
#define ID_MAPMENU_TERRAIN_UNDERGROUNDWILD 32901
#define ID_MAPMENU_TERRAIN_UNDERGROUNDCITY 32902
#define ID_MAPMENU_TERRAIN_UNDERGROUNDINSIDE 32903
#define ID_MAPMENU_TERRAIN_UNDERGROUNDWATER 32904
#define ID_MAPMENU_TERRAIN_UNDERGROUNDNOSWIM 32905
#define ID_MAPMENU_TERRAIN_UNDERGROUNDAIR 32906
#define ID_MAPMENU_TERRAIN_FIREPLANE    32907
#define ID_MAPMENU_TERRAIN_AIRPLANE     32908
#define ID_MAPMENU_TERRAIN_WATERPLANE   32909
#define ID_MAPMENU_TERRAIN_EARTHPLANE   32910
#define ID_MAPMENU_TERRAIN_ETHEREALPLANE 32911
#define ID_MAPMENU_TERRAIN_ASTRALPLANE  32912
#define ID_MAPMENU_TERRAIN_DESERT       32913
#define ID_MAPMENU_TERRAIN_ARCTIC       32914
#define ID_MAPMENU_TERRAIN_SWAMP        32915
#define ID_MAPMENU_TERRAIN_ROAD         32916
#define ID_MAPMENU_TERRAIN_UNDERGROUNDNOPASS 32917
#define ID_MAPMENU_TERRAIN_UNDERGROUNDOCEAN 32918
#define ID_MAPMENU_MOBILES_ADDMOBILE    32919
#define ID_MAPMENU_CONTENTS_ADDITEM     32920
#define ID_EDITMENU_EDIT                32921
#define ID_EDITMENU_DELETE              32922
#define ID__OBJPOPUP                    32923
#define ID_OBJPOPUP_OBJECT_EDIT         32924
#define ID_OBJPOPUP_OBJECT_REMOVEFROMROOM 32925
#define ID_MOBPOPUP_EDITMOB             32926
#define ID_MOBPOPUP_REMOVEFROMROOM      32927
#define ID_INVPOPUP_EQUIP               32928
#define ID_INVPOPUP_REMOVEFROMMOB       32929
#define ID_CONTENTPOPUP_EDITOBJECT      32930
#define ID_CONTENTPOPUP_REMOVEFROMOBJECT 32931
#define ID_INVPOPUP_EDITOBJECT          32932
#define ID_BITCALC                      32933

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        366
#define _APS_NEXT_COMMAND_VALUE         32934
#define _APS_NEXT_CONTROL_VALUE         1535
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
