#include "StdAfx.h"
#include "Spells.h"

const Type types[TYPE_MAX] =
{
	{TYPE_ALL,			"All Spells"},
	{TYPE_DEFENSIVE,	"Defensive Spells"},
	{TYPE_OFFENSIVE,	"Offensive Spells"},
	{TYPE_AREA,			"Area Spells"},
	{TYPE_SELF,			"Self Only Spells"},
	{TYPE_MISC,			"Misc. Spells"},
	{TYPE_OBJECT,		"Object Spells"},
	{TYPE_WALLS,		"Walls"},
	{TYPE_TRANSPORT,	"Transport Spells"},
};

Spell spells[SPELL_HIGHEST] =
{
	{0,									-1,				true,	 "None"},
	{SPELL_ARMOR,						TYPE_DEFENSIVE, true,	 "Armor"},
	{SPELL_TELEPORT,					TYPE_TRANSPORT,	true,	 "Teleport"},
	{SPELL_BLESS,						TYPE_DEFENSIVE, true,	 "Bless"},
	{SPELL_BLINDNESS,					TYPE_OFFENSIVE, true,	 "Blindness"},
	{SPELL_BURNING_HANDS,				TYPE_OFFENSIVE, true,	 "Burning Hands"},
	{SPELL_CALL_LIGHTNING,				TYPE_OFFENSIVE, true,	 "Call Lightning"},
	{SPELL_CHARM_PERSON,				TYPE_OFFENSIVE, false,	 "Charm Person"},
	{SPELL_CHILL_TOUCH,					TYPE_OFFENSIVE, true,	 "Chill Touch"},
	{SPELL_FULL_HEAL,					TYPE_DEFENSIVE, true,	 "Full Heal"},
	{SPELL_CONE_OF_COLD,				TYPE_OFFENSIVE, true,	 "Cone of Cold"},
	{SPELL_CONTROL_WEATHER,				TYPE_MISC,		true,	 "Control Weather"},
	{SPELL_CREATE_FOOD,					TYPE_MISC,		true,	 "Create Food"},
	{SPELL_CREATE_WATER,				TYPE_MISC,		true,	 "Create Water"},
	{SPELL_CURE_BLIND,					TYPE_DEFENSIVE, true,	 "Cure Blind"},
	{SPELL_CURE_CRITIC,					TYPE_DEFENSIVE, true,	 "Cure Critic"},
	{SPELL_CURE_LIGHT,					TYPE_DEFENSIVE, true,	 "Cure Light Wounds"},
	{SPELL_CURSE,						TYPE_OFFENSIVE, true,	 "Curse"},
	{SPELL_CONTINUAL_LIGHT,				TYPE_MISC,		true,	 "Continual Light"},
	{SPELL_DETECT_INVISIBLE,			TYPE_DEFENSIVE, true,    "Detect Invisible"},
	{SPELL_MINOR_CREATION,				TYPE_MISC,		true,    "Minor Creation"},
	{SPELL_FLAMESTRIKE,					TYPE_OFFENSIVE, true,    "Flame Strike"},
	{SPELL_DISPEL_EVIL,					TYPE_OFFENSIVE, true,    "Dispel Evil"},
	{SPELL_EARTHQUAKE,					TYPE_AREA,		true,    "Earthquake"},
	{SPELL_ENCHANT_WEAPON,				TYPE_OBJECT,	true,    "Enchant Weapon"},
	{SPELL_ENERGY_DRAIN,				TYPE_OFFENSIVE, true,    "Energy Drain"},
	{SPELL_FIREBALL,					TYPE_OFFENSIVE, true,    "Fireball"},
	{SPELL_HARM,						TYPE_OFFENSIVE, true,    "Harm"},
	{SPELL_HEAL,						TYPE_DEFENSIVE, true,    "Heal"},
	{SPELL_INVISIBLE,					TYPE_DEFENSIVE, true,    "Invisiblility"},
	{SPELL_LIGHTNING_BOLT,				TYPE_OFFENSIVE, true,    "Lightning Bolt"},
	{SPELL_LOCATE_OBJECT,				TYPE_OBJECT,	true,    "Locate Object"},
	{SPELL_MAGIC_MISSILE,				TYPE_OFFENSIVE, true,    "Magic Missile"},
	{SPELL_POISON,						TYPE_OFFENSIVE, true,    "Poison"},
	{SPELL_PROTECT_FROM_EVIL,			TYPE_DEFENSIVE, true,    "Protection From Evil"},
	{SPELL_REMOVE_CURSE,				TYPE_DEFENSIVE, true,    "Remove Curse"},
    {SPELL_STONE_SKIN,					TYPE_DEFENSIVE, true,    "Stone Skin"},
	{SPELL_SHOCKING_GRASP,				TYPE_OFFENSIVE, true,    "Shocking Grasp"},
	{SPELL_SLEEP,						TYPE_OFFENSIVE, true,    "Sleep"},
	{SPELL_STRENGTH,					TYPE_DEFENSIVE, true,    "Strength"},
	{SPELL_SUMMON,						TYPE_TRANSPORT,	true,    "Summon"},
	{SPELL_HASTE,						TYPE_DEFENSIVE, true,    "Haste"},
	{SPELL_WORD_OF_RECALL,				TYPE_TRANSPORT,	true,    "Word of Recall"},
	{SPELL_REMOVE_POISON,				TYPE_DEFENSIVE, true,    "Remove Poison"},
	{SPELL_SENSE_LIFE,					TYPE_SELF,		true,    "Sense Life"},
	{SPELL_IDENTIFY,					TYPE_OBJECT,	true,    "Identify"},
	{SPELL_VENTRILOQUATE,				TYPE_MISC,		true,    "Ventriloquate"},
	{SPELL_FIRESTORM,					TYPE_AREA,		true,    "Firestorm"},
	{SPELL_FIRE_BREATH,					TYPE_AREA,		true,    "Fire Breath"},
	{SPELL_GAS_BREATH,					TYPE_AREA,		true,    "Gas Breath"},
	{SPELL_FROST_BREATH,				TYPE_AREA,		true,    "Frost Breath"},
	{SPELL_ACID_BREATH,					TYPE_AREA,		true,    "Acid Breath"},
	{SPELL_LIGHTNING_BREATH,			TYPE_AREA,		true,    "Lightning Breath"},
    {SPELL_FARSEE,						TYPE_SELF,		true,    "Farsee"},
	{SPELL_FEAR,						TYPE_OFFENSIVE, true,    "Fear"},
	{SPELL_RECHARGER,					TYPE_MISC,		false,   "Recharge"},
	{SPELL_VITALITY,					TYPE_DEFENSIVE, true,    "Vitality"},
	{SPELL_CURE_SERIOUS,				TYPE_DEFENSIVE, true,    "Cure Serious"},
	{SPELL_DESTROY_UNDEAD,				TYPE_OFFENSIVE, true,    "Destroy Undead"},
	{SPELL_METEOR_SWARM,				TYPE_AREA,		true,    "Meteor Swarm"},
	{SPELL_CREEPING,					TYPE_AREA,		true,    "Creeping Doom"},
	{SPELL_MINOR_GLOBE,					TYPE_DEFENSIVE, true,    "Minor Globe"},
	{SPELL_CHAIN_LIGHTNING,				TYPE_AREA,		true,    "Chain Lightning"},
	{SPELL_DIMENSION_DOOR,				TYPE_TRANSPORT,	true,    "Dimension Door"},
	{SPELL_VIGORIZE_LIGHT,				TYPE_DEFENSIVE, true,    "Vigorize Light"},
	{SPELL_VIGORIZE_SERIOUS,			TYPE_DEFENSIVE, true,    "Vigorize Serious"},
	{SPELL_VIGORIZE_CRITIC,				TYPE_DEFENSIVE, true,    "Vigorize Critical"},
	{SPELL_DISPEL_INVISIBLE,			TYPE_MISC,		true,    "Dispel Invisible"},
	{SPELL_WIZARD_EYE,					TYPE_MISC,		true,    "Wizard Eye"},
	{SPELL_CLAIRVOYANCE,				TYPE_MISC,		true,    "Clairvoyance"},
	{SPELL_REJUVENATE_MAJOR	,			TYPE_MISC,		true,    "Rejuvenate Major"},
	{SPELL_RAY_OF_ENFEEBLEMENT,			TYPE_OFFENSIVE, true,    "Ray of Enfeeblement"},
	{SPELL_DISPEL_GOOD,					TYPE_OFFENSIVE, true,    "Dispel Good"},
	{SPELL_DEXTERITY,					TYPE_DEFENSIVE, true,    "Dexterity"},
	{SPELL_REJUVENATE_MINOR,			TYPE_MISC,		true,    "Rejuvenate Minor"},
    {SPELL_AGE,							TYPE_MISC,		true,    "Age"},
	{SPELL_CYCLONE,						TYPE_AREA,		true,    "Cyclone"},
	{SPELL_BIGBYS_CLENCHED_FIST,		TYPE_OFFENSIVE, true,    "Bigbys Clenched Fist"},
	{SPELL_CONJURE_ELEMENTAL,			TYPE_MISC,		true,    "Conjure Elemental"},
	{SPELL_VITALIZE_MANA,				TYPE_DEFENSIVE, true,    "Vitalize Mana"},
	{SPELL_RELOCATE,					TYPE_TRANSPORT,	true,    "Relocate"},
	{SPELL_PROTECT_FROM_GOOD,			TYPE_DEFENSIVE, true,    "Protection From Good"},
	{SPELL_ANIMATE_DEAD,				TYPE_OBJECT,	true,    "Animate Dead"},
	{SPELL_LEVITATE,					TYPE_DEFENSIVE, true,    "Levitate"},
	{SPELL_FLY,							TYPE_DEFENSIVE, true,    "Fly"},
	{SPELL_WATERBREATH,					TYPE_MISC,		true,    "Water Breath"},
	{SPELL_PLANE_SHIFT,					TYPE_TRANSPORT,	true,    "Plane Shift"},
	{SPELL_GATE,						TYPE_TRANSPORT,	true,    "Gate"},
	{SPELL_RESURRECT,					TYPE_OBJECT,	true,    "Resurrect"},
	{SPELL_MASS_CHARM,					TYPE_AREA,		true,    "Mass Charm"},
	{SPELL_DETECT_EVIL,					TYPE_DEFENSIVE, true,    "Detect Evil"},
	{SPELL_DETECT_GOOD,					TYPE_DEFENSIVE, true,    "Detect Good"},
	{SPELL_DETECT_MAGIC,				TYPE_DEFENSIVE, true,    "Detect Magic"},
	{SPELL_DISPEL_MAGIC,				TYPE_DEFENSIVE, true,    "Dispel Magic"},
	{SPELL_PRESERVE	,					TYPE_MISC,		true,    "Preserve"},
	{SPELL_MASS_INVIS,					TYPE_DEFENSIVE, true,    "Mass Invisibility"},
	{SPELL_PROTECT_FROM_FIRE,			TYPE_DEFENSIVE, true,    "Protection From Fire"},
	{SPELL_PROTECT_FROM_COLD,			TYPE_DEFENSIVE, true,    "Protection From Cold"},
	{SPELL_PROTECT_FROM_LIGHTNING,		TYPE_DEFENSIVE, true,    "Protection From Lightning"},
	{SPELL_DARKNESS,					TYPE_MISC,		true,    "Darkness"},
	{SPELL_MINOR_PARALYSIS,				TYPE_OFFENSIVE, true,    "Minor Paralysis"},
	{SPELL_MAJOR_PARALYSIS,				TYPE_OFFENSIVE, true,    "Major Paralysis"},
	{SPELL_SLOW,						TYPE_OFFENSIVE, true,    "Slow"},
	{SPELL_WITHER,						TYPE_OFFENSIVE, true,    "Wither"},
	{SPELL_PROTECT_FROM_GAS,			TYPE_DEFENSIVE, true,    "Protection From Gas"},
	{SPELL_PROTECT_FROM_ACID,			TYPE_DEFENSIVE, true,    "Protection From Acid"},
	{SPELL_INFRAVISION,					TYPE_MISC,		true,    "Infravision"},
	{SPELL_PRISMATIC_SPRAY,				TYPE_OFFENSIVE, true,    "Prismatic Spray"},
	{SPELL_FIRESHIELD,					TYPE_SELF,		true,    "Fireshield"},
	{SPELL_COLOR_SPRAY,					TYPE_OFFENSIVE, true,    "Color Spray"},
	{SPELL_INCENDIARY_CLOUD,			TYPE_AREA,		true,    "Incendiary Cloud"},
	{SPELL_ICE_STORM,					TYPE_AREA,		true,    "Ice Storm"},
	{SPELL_DISINTEGRATE,				TYPE_OFFENSIVE, true,    "Disintegrate"},
	{SPELL_CAUSE_LIGHT,					TYPE_OFFENSIVE, true,    "Cause Light"},
	{SPELL_CAUSE_SERIOUS,				TYPE_OFFENSIVE, true,    "Cause Serious"},
	{SPELL_CAUSE_CRITICAL,				TYPE_OFFENSIVE, true,    "Cause Critical"},
	{SPELL_ACID_BLAST,					TYPE_OFFENSIVE, true,    "Acid Blast"},
	{SPELL_FAERIE_FIRE,					TYPE_OFFENSIVE, true,    "Faerie Fire"},
	{SPELL_FAERIE_FOG,					TYPE_AREA,		true,    "Faerie Fog"},
	{SPELL_PWORD_KILL,					TYPE_OFFENSIVE, true,    "Power Word Kill"},
	{SPELL_PWORD_BLIND,					TYPE_OFFENSIVE, true,    "Power Word Blind"},
	{SPELL_PWORD_STUN,					TYPE_OFFENSIVE, true,    "Power Word Stun"},
	{SPELL_UNHOLY_WORD,					TYPE_AREA,		true,    "Un-Holy Word"},
	{SPELL_HOLY_WORD,					TYPE_AREA,		true,    "Holy Word"},
	{SPELL_SUNRAY,						TYPE_OFFENSIVE, true,    "Sunray"},
	{SPELL_UNKNOWN,						TYPE_MISC,		false,	 "Unknown"},
	{SPELL_FEEBLEMIND,					TYPE_OFFENSIVE, true,    "Feeblemind"},
	{SPELL_SILENCE,						TYPE_OFFENSIVE, true,    "Silence"},
	{SPELL_TURN_UNDEAD,					TYPE_OFFENSIVE, true,    "Turn Undead"},
	{SPELL_COMMAND_UNDEAD,				TYPE_MISC,		true,    "Command Undead"},
	{SPELL_SLOW_POISON,					TYPE_DEFENSIVE, true,    "Slow Poison"},
	{SPELL_COLDSHIELD,					TYPE_SELF,		true,    "Coldshield"},
	{SPELL_COMPREHEND_LANGUAGES,		TYPE_MISC,		true,    "Comprehend Languages"},
	{SPELL_WRAITHFORM,					TYPE_SELF,		true,    "Wraithform"},
	{SPELL_VAMPIRIC_TOUCH,				TYPE_SELF,		true,    "Vampiric Touch"},
	{SPELL_PROT_UNDEAD ,				TYPE_DEFENSIVE, true,    "Protect Undead"},
	{SPELL_PROT_FROM_UNDEAD,			TYPE_DEFENSIVE, true,    "Protection From Undead"},
	{SPELL_COMMAND_HORDE,				TYPE_MISC,		true,    "Command Hoarde"},
	{SPELL_HEAL_UNDEAD,					TYPE_DEFENSIVE, true,    "Heal Undead"},
	{SPELL_ENTANGLE ,					TYPE_OFFENSIVE, true,    "Entangle"},
	{SPELL_CREATE_SPRING,				TYPE_MISC,		true,    "Create Spring"},
	{SPELL_BARKSKIN,					TYPE_DEFENSIVE, true,    "Barkskin"},
	{SPELL_MOONWELL ,					TYPE_TRANSPORT,	true,    "Moonwell"},
	{SPELL_CREATE_DRACOLICH,			TYPE_OBJECT,	true,    "Create Dracolich"},
	{SPELL_GLOBE,						TYPE_DEFENSIVE, true,    "Globe of Invulnerability"},
	{SPELL_EMBALM,						TYPE_MISC,		true,    "Embalm"},
	{SPELL_SHADOW_BREATH_1,				TYPE_AREA,		true,    "Shadow Breath1"},
    {SPELL_SHADOW_BREATH_2,				TYPE_AREA,		true,    "Shadow Breath2"},
	{SPELL_WALL_OF_FLAMES,				TYPE_WALLS,		true,    "Wall of Flames"},
	{SPELL_WALL_OF_ICE,					TYPE_WALLS,		true,    "Wall of Ice"},
	{SPELL_WALL_OF_STONE,				TYPE_WALLS,		true,    "Wall of Stone"},
	{SPELL_WALL_OF_IRON,				TYPE_WALLS,		true,    "Wall of Iron"},
	{SPELL_WALL_OF_FORCE,				TYPE_WALLS,		true,    "Wall of Force"},
	{SPELL_WALL_OF_BONES,				TYPE_WALLS,		true,    "Wall of Bones"},
	{SPELL_LIGHTNING_CURTAIN,			TYPE_WALLS,		true,    "Lightning Curtain"},
	{SPELL_MOLECULAR_CONTROL,			TYPE_SELF,		true,    "Molecular Control"},
	{SPELL_MOLECULAR_AGITATION,			TYPE_SELF,		true,    "Molecular Agitation"},
	{SPELL_ADRENALINE_CONTROL,			TYPE_SELF,		true,    "Adrenaline Control"},
	{SPELL_AURA_SIGHT,					TYPE_SELF,		true,    "Aura Sight"},
	{SPELL_AWE ,						TYPE_MISC,		true,    "Awe"},
	{SPELL_BALLISTIC_ATTACK,			TYPE_OFFENSIVE, true,    "Ballistic Attack"},
	{SPELL_BIOFEEDBACK,					TYPE_SELF,		true,    "Biofeedback"},
	{SPELL_CELL_ADJUSTMENT,				TYPE_SELF,		true,    "Cell Adjustment"},
	{SPELL_COMBAT_MIND,					TYPE_SELF,		true,    "Combat Mind"},
	{SPELL_CONTROL_FLAMES,				TYPE_MISC,		true,    "Control Flames"},
	{SPELL_CREATE_SOUND,				TYPE_MISC,		true,    "Create Sound"},
	{SPELL_DEATH_FIELD,					TYPE_AREA,		true,    "Death Field"},
	{SPELL_DETONATE,					TYPE_OFFENSIVE, true,    "Detonate"},
	{SPELL_DISINTEGRATE2,				TYPE_OFFENSIVE, true,    "Disintegrate2"},
	{SPELL_DISPLACEMENT,				TYPE_SELF,		true,    "Displacement"},
	{SPELL_DOMINATION,					TYPE_OFFENSIVE, true,    "Domination"},
	{SPELL_ECTOPLASMIC_FORM,			TYPE_SELF,		true,    "Ectoplasmic Form"},
	{SPELL_EGO_WHIP,					TYPE_OFFENSIVE, true,    "Ego Whip"},
	{SPELL_ENERGY_CONTAINMENT,			TYPE_SELF,		true,    "Energy Containment"},
	{SPELL_ENHANCE_ARMOR,				TYPE_SELF,		true,    "Enhance Armor"},
	{SPELL_ENHANCED_STR,				TYPE_SELF,		true,    "Enhanced Strength"},
	{SPELL_ENHANCED_DEX,				TYPE_SELF,		true,    "Enhanced Dexterity"},
	{SPELL_ENHANCED_AGI ,				TYPE_SELF,		true,    "Enhanced Agility"},
	{SPELL_ENHANCED_CON,				TYPE_SELF,		true,    "Enhanced Constitution"},
	{SPELL_FLESH_ARMOR,					TYPE_SELF,		true,    "Flesh Armor"},
	{SPELL_INERTIAL_BARRIOR,			TYPE_SELF,		true,    "Inertial Barrier"},
	{SPELL_INFLICT_PAIN,				TYPE_OFFENSIVE, true,    "Inflict Pain"},
	{SPELL_INTELLECT_FORTRESS,			TYPE_DEFENSIVE, true,    "Intellect Fortress"},
	{SPELL_LEND_HEALTH,					TYPE_DEFENSIVE, true,    "Lend Health"},
	{SPELL_LEVITATION,					TYPE_DEFENSIVE, true,    "Levitation"},
	{SPELL_CONFUSE,						TYPE_OFFENSIVE, true,    "Confuse"},
	{SPELL_DISEASE,						TYPE_OFFENSIVE, true,    "Disease"},
	{SPELL_CHARM_ANIMAL,				TYPE_OFFENSIVE, true,    "Charm Animal"},
	{SPELL_SOULSHIELD ,					TYPE_DEFENSIVE, true,    "Soulshield"},
	{SPELL_INVIS_MAJOR,					TYPE_DEFENSIVE, false,   "Invis Major"},
	{SPELL_MASS_HEAL,					TYPE_DEFENSIVE, true,    "Mass Heal"},
	{SPELL_ICE_MISSILE,					TYPE_OFFENSIVE, true,    "Ice Missile"},
	{SPELL_SPIRIT_ARMOR,				TYPE_DEFENSIVE, true,    "Spirit Armor"},
	{SPELL_WOLFSPEED,					TYPE_DEFENSIVE, true,    "Wolfspeed"},
	{SPELL_TRANSFER_WELLNESS,			TYPE_DEFENSIVE, true,    "Transfer Wellness"},
	{SPELL_FLAMEBURST,					TYPE_OFFENSIVE, true,    "Flameburst"},
	{SPELL_SCALDING_BLAST,				TYPE_OFFENSIVE, true,    "Scalding Blast"},
	{SPELL_PYTHONSTING,					TYPE_OFFENSIVE, true,    "Pythonsting"},
	{SPELL_SNAILSPEED,					TYPE_OFFENSIVE, true,    "Snail Speed"},
	{SPELL_MOLEVISION,					TYPE_OFFENSIVE, true,    "Molevision"},
	{SPELL_PURIFY_SPIRIT,				TYPE_OFFENSIVE, true,    "Purify Spirit"},
	{SPELL_PANTHERSPEED,				TYPE_DEFENSIVE, true,    "Panther Speed"},
	{SPELL_MOUSESTRENGTH,				TYPE_OFFENSIVE, true,    "Mouse Strength"},
	{SPELL_SUMMON_BEAST,				TYPE_MISC,		true,    "Summon Beast"},
	{SPELL_HAWKVISION,					TYPE_DEFENSIVE, true,    "Hawk Vision"},
	{SPELL_SCORCHING_TOUCH,				TYPE_OFFENSIVE, true,    "Scorching Touch"},
	{SPELL_MENDING,						TYPE_DEFENSIVE, true,    "Mending"},
	{SPELL_SOUL_DISTURBANCE,			TYPE_OFFENSIVE, true,    "Soul Disturbance"},
	{SPELL_SPIRIT_SIGHT,				TYPE_DEFENSIVE, true,    "Spirit Sight"},
	{SPELL_BEARSTRENGTH,				TYPE_DEFENSIVE, true,    "Bear Strength"},
	{SPELL_SHREWTAMENESS,				TYPE_OFFENSIVE, true,    "Shrew Tameness"},
	{SPELL_SENSE_SPIRIT,				TYPE_DEFENSIVE, true,    "Sense Spirit"},
	{SPELL_MALISON,						TYPE_OFFENSIVE, true,    "Malison"},
	{SPELL_WELLNESS,					TYPE_DEFENSIVE, true,    "Wellness"},
	{SPELL_GREATER_MENDING,				TYPE_DEFENSIVE, true,    "Greater Mending"},
	{SPELL_LIONRAGE,					TYPE_DEFENSIVE, true,    "Lion Rage"},
	{SPELL_SPIRIT_ANGUISH,				TYPE_OFFENSIVE, true,    "Spirit Anguish"},
	{SPELL_EARTHEN_GRASP,				TYPE_OFFENSIVE, true,    "Earthen Grasp"},
	{SPELL_SUMMON_SPIRIT,				TYPE_MISC,		true,    "Summon Spirit"},
	{SPELL_GREATER_SOUL_DISTURB,		TYPE_OFFENSIVE, true,    "Greater Soul Disturbance"},
	{SPELL_SPIRIT_WARD,					TYPE_DEFENSIVE, true,    "Spirit Ward"},
	{SPELL_ELEPHANTSTRENGTH,			TYPE_DEFENSIVE, true,    "Elephant Strength"},
	{SPELL_GREATER_PYTHONSTING,			TYPE_AREA,		true,    "Greater Python Sting"},
	{SPELL_SCATHING_WIND,				TYPE_AREA,		true,    "Scathing Wind"},
	{SPELL_REVEAL_TRUE_FORM,			TYPE_MISC,		true,    "Reveal True Form"},
	{SPELL_GREATER_SPIRIT_SIGHT,		TYPE_DEFENSIVE, true,    "Greater Spirit Sight"},
	{SPELL_EARTHEN_RAIN,				TYPE_AREA,		true,    "Earthen Rain"},
	{SPELL_GREATER_SPIRIT_WARD,			TYPE_DEFENSIVE, true,    "Greater Spirit Ward"},
    {SPELL_SUSTENANCE,					TYPE_MISC,		true,    "Sustenance"},
	{SPELL_CREATE_EARTHEN_PROJ,			TYPE_MISC,		false,   "Create Earthen Projection"},
	{SPELL_ANIMATE_EARTHEN_PROJ,		TYPE_MISC,		false,   "Animate Earthen Projection"},
	{SPELL_GREATER_SUST,				TYPE_MISC,		true,    "Greater Sustenance"},
	{SPELL_COLD_WARD,					TYPE_DEFENSIVE, true,    "Cold Ward"},
	{SPELL_FIRE_WARD,					TYPE_DEFENSIVE, true,    "Fire Ward"},
	{SPELL_LESSER_MENDING,				TYPE_DEFENSIVE, true,    "Lesser Mending"},
	{SPELL_MOLTEN_SPRAY,				TYPE_OFFENSIVE, true,    "Molten Spray"},
	{SPELL_TRUE_SEEING,					TYPE_SELF,		true,    "True Seeing"},
	{SPELL_BOGUS_TEST,					TYPE_MISC,		false,   "Bogus Test"},
	{SPELL_RAVENFLIGHT ,				TYPE_DEFENSIVE, true,    "Raven Flight"},
	{SPELL_GREATER_RAVENFLIGHT,			TYPE_DEFENSIVE, true,    "Greater Raven Flight"},
	{SPELL_LORE,						TYPE_OBJECT,	true,    "Lore"},
	{SPELL_WORMHOLE,					TYPE_TRANSPORT,	true,    "Wormhole"},
	{SPELL_ETHERPORTAL,					TYPE_TRANSPORT,	true,    "Etherportal"},
	{SPELL_FULL_HARM,					TYPE_OFFENSIVE, true,    "Full Harm"},
	{SPELL_CONJURE_GREATER_ELEMENTAL,	TYPE_MISC,		true,    "Conjure Greater Elemental"},
	{SPELL_GROUP_RECALL,				TYPE_DEFENSIVE,	true,    "Group Recall"},
	{SPELL_GREATER_EARTHEN_GRASP,		TYPE_AREA,		true,    "Greater Earthen Grasp"},
	{SPELL_GROUP_STONE_SKIN ,			TYPE_DEFENSIVE, true,    "Group Stone Skin"},
	{SPELL_ENLARGE,						TYPE_MISC,		true,    "Enlarge"},
	{SPELL_REDUCE,						TYPE_MISC,		true,    "Reduce"},
	{SPELL_REVEAL_SPIRIT_ESSENCE,		TYPE_MISC,		true,    "Reveal Spirit Essence"},
	{SPELL_SPIRIT_JUMP,					TYPE_TRANSPORT,	true,    "Spirit Jump"},
    {SPELL_BEHOLDER_DISIN,				TYPE_MISC,		false,   "Beholder Disintegrate"},
	{SPELL_BEHOLDER_DAMAGE,				TYPE_MISC,		false,   "Beholder Damage"},
	{SPELL_ARIEKS_SHATTERING_ICEBALL,	TYPE_OFFENSIVE,	true,	 "Arieks Shattering Iceball"},
	{SPELL_ENRAGE,						TYPE_OFFENSIVE, true,    "Enrage"},
	{SPELL_BLINDING_BREATH,				TYPE_OFFENSIVE, true,    "Blinding Breath"},
	{SPELL_MIND_BLANK,					TYPE_SELF,		true,    "Mind Blank"},
	{SPELL_SIGHT_LINK,					TYPE_MISC,		true,    "Sight Link"},
	{SPELL_CANIBALIZE,					TYPE_OFFENSIVE, true,    "Canibalize"},
	{SPELL_TOWER_IRON_WILL,				TYPE_SELF,		true,    "Tower of Iron Will"},
	{SPELL_MIRROR_IMAGE,				TYPE_SELF,		true,    "Mirror Image"},
	{SPELL_REVEAL_TRUE_NAME,			TYPE_OBJECT,	true,    "Reveal True Name"},
	{SPELL_BLUR,						TYPE_SELF,		true,    "Blur"},
	{SPELL_PRISMATIC_CUBE,				TYPE_AREA,		true,    "Prismatic Cube"},
	{SPELL_JUDGEMENT,					TYPE_AREA,		true,    "Judgement"},
	{SPELL_GREATER_WRAITHFORM,			TYPE_SELF,		true,    "Greater Wraithform"},
	{SPELL_ELEMENTAL_FORM,				TYPE_SELF,		true,    "Elemental Form"},
	{SPELL_RAISE_SPECTRE,				TYPE_OBJECT,	true,    "Raise Spectre"},
	{SPELL_RAISE_WRAITH,				TYPE_OBJECT,	true,    "Raise Wraith"},
	{SPELL_RAISE_VAMPIRE,				TYPE_OBJECT,	true,    "Raise Vampire"},
	{SPELL_RAISE_LICH,					TYPE_OBJECT,	true,    "Raise Lich"},
    {SPELL_PALADIN_AURA,				TYPE_MISC,		false,   "Paladin Aura"},
	{SPELL_MINDSHIELD,					TYPE_SELF,		true,    "Mindshield"},
	{SPELL_AIRY_WATER,					TYPE_AREA,		true,    "Airy Water"},
	{SPELL_CURE_DISEASE,				TYPE_DEFENSIVE, true,    "Cure Disease"},
	{SPELL_POLYMORPH_OBJECT,			TYPE_MISC,		true,    "Polymorph Object"},
	{SPELL_IMMOLATE,					TYPE_OFFENSIVE, true,    "Immolate"},
	{SPELL_APOCALYPSE,					TYPE_AREA,		true,    "Apocalypse"},
	{SPELL_SENSE_FOLLOWER,				TYPE_SELF,		true,    "Sense Follower"},
	{SPELL_PASS_WITHOUT_TRACE,			TYPE_SELF,		true,    "Pass Without Trace"},
	{SPELL_ETHER_WARP,					TYPE_MISC,		true,    "Ether Warp"},
	{SPELL_STARSHELL,					TYPE_MISC,		true,    "Starshell"},
	{SPELL_CLOAK_OF_FEAR,				TYPE_AREA,		true,    "Cloak of Fear"},
	{SPELL_VAMPIRE ,					TYPE_MISC,		false,   "Vampire"},
	{SPELL_BIGBYS_CRUSHING_HAND,		TYPE_OFFENSIVE, true,    "Bigbys Crushing Hand"},
	{SPELL_STORNOGS_SPHERES,			TYPE_SELF,		true,    "Stornogs Spheres"},
	{SPELL_STORNOGS_GREATER_SPHERES,	TYPE_SELF,		true,    "Stornogs Greater Spheres"},
	{SPELL_GROUP_GLOBE,					TYPE_DEFENSIVE,	true,    "Group Globe"},
	{SPELL_ETHER_SENSE ,				TYPE_SELF,		true,    "Ether Sense"},
	{SPELL_CALL_OF_THE_WILD ,			TYPE_OFFENSIVE, true,    "Call of the Wild"},
	{SPELL_HOLY_SACRIFICE,				TYPE_SELF,		true,    "Holy Sacrifice"},
	{SPELL_BATTLE_ECSTASY,				TYPE_SELF,		true,    "Battle Ecstasy"},
	{SPELL_DAZZLE,						TYPE_SELF,		true,    "Dazzle"},
};