// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vcaxisgrid.h"

// Dispatch interfaces referenced by this interface
#include "VcPen.h"


/////////////////////////////////////////////////////////////////////////////
// CVcAxisGrid properties

/////////////////////////////////////////////////////////////////////////////
// CVcAxisGrid operations

CVcPen CVcAxisGrid::GetMinorPen()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CVcPen(pDispatch);
}

CVcPen CVcAxisGrid::GetMajorPen()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CVcPen(pDispatch);
}
