#if !defined(AFX_VCAXISGRID_H__CF803E47_DCE3_420D_B80B_E3DB1878E977__INCLUDED_)
#define AFX_VCAXISGRID_H__CF803E47_DCE3_420D_B80B_E3DB1878E977__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcPen;

/////////////////////////////////////////////////////////////////////////////
// CVcAxisGrid wrapper class

class CVcAxisGrid : public COleDispatchDriver
{
public:
	CVcAxisGrid() {}		// Calls COleDispatchDriver default constructor
	CVcAxisGrid(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcAxisGrid(const CVcAxisGrid& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CVcPen GetMinorPen();
	CVcPen GetMajorPen();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCAXISGRID_H__CF803E47_DCE3_420D_B80B_E3DB1878E977__INCLUDED_)
