#if !defined(AFX_VCAXISSCALE_H__5DF3AC2F_F8A3_4BEC_AE21_BADBE7CA0BD3__INCLUDED_)
#define AFX_VCAXISSCALE_H__5DF3AC2F_F8A3_4BEC_AE21_BADBE7CA0BD3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcAxisScale wrapper class

class CVcAxisScale : public COleDispatchDriver
{
public:
	CVcAxisScale() {}		// Calls COleDispatchDriver default constructor
	CVcAxisScale(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcAxisScale(const CVcAxisScale& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetHide();
	void SetHide(BOOL bNewValue);
	long GetType();
	void SetType(long nNewValue);
	short GetLogBase();
	void SetLogBase(short nNewValue);
	long GetPercentBasis();
	void SetPercentBasis(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCAXISSCALE_H__5DF3AC2F_F8A3_4BEC_AE21_BADBE7CA0BD3__INCLUDED_)
