// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vcbackdrop.h"

// Dispatch interfaces referenced by this interface
#include "vcshadow.h"
#include "vcframe.h"
#include "vcfill.h"


/////////////////////////////////////////////////////////////////////////////
// CVcBackdrop properties

/////////////////////////////////////////////////////////////////////////////
// CVcBackdrop operations

CVcShadow CVcBackdrop::GetShadow()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CVcShadow(pDispatch);
}

CVcFrame CVcBackdrop::GetFrame()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CVcFrame(pDispatch);
}

CVcFill CVcBackdrop::GetFill()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CVcFill(pDispatch);
}
