#if !defined(AFX_VCLIGHTSOURCE_H__D8111B57_3BC1_4810_A64D_0C535C07BFBE__INCLUDED_)
#define AFX_VCLIGHTSOURCE_H__D8111B57_3BC1_4810_A64D_0C535C07BFBE__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVcLightSource wrapper class

class CVcLightSource : public COleDispatchDriver
{
public:
	CVcLightSource() {}		// Calls COleDispatchDriver default constructor
	CVcLightSource(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcLightSource(const CVcLightSource& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	float GetIntensity();
	void SetIntensity(float newValue);
	float GetX();
	void SetX(float newValue);
	float GetY();
	void SetY(float newValue);
	float GetZ();
	void SetZ(float newValue);
	void Set(float X, float Y, float Z, float Intensity);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCLIGHTSOURCE_H__D8111B57_3BC1_4810_A64D_0C535C07BFBE__INCLUDED_)
