// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vcrect.h"

// Dispatch interfaces referenced by this interface
#include "vccoor.h"


/////////////////////////////////////////////////////////////////////////////
// CVcRect properties

/////////////////////////////////////////////////////////////////////////////
// CVcRect operations

CVcCoor CVcRect::GetMin()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CVcCoor(pDispatch);
}

CVcCoor CVcRect::GetMax()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CVcCoor(pDispatch);
}
