// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vcseriescollection.h"

// Dispatch interfaces referenced by this interface
#include "vcseries.h"


/////////////////////////////////////////////////////////////////////////////
// CVcSeriesCollection properties

/////////////////////////////////////////////////////////////////////////////
// CVcSeriesCollection operations

long CVcSeriesCollection::Count()
{
	long result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CVcSeries CVcSeriesCollection::GetItem(short Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return CVcSeries(pDispatch);
}
